services:
  - postgresql
  
language: node_js

node_js:
  - "5"
  
before_script:
  - psql -c 'create database travis;' -U postgres
  - echo "var config = require('./server/db/config'); setTimeout(function(){process.exit();}, 5000)" | node
